### ISSUE TITLE
Mozambique - Broken Datapack

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#107]
Aaron to provide additional details.

**Comment by achafetz** [comment]
Moz ran into an issue when sorting their DATIM Indicator table. 

All SNU lists are linked to the DATIM Indicator table, so when it is sorted, all the others sort. This is fine when all the other columns are formulas. When something is hard coded, it remains fixed in place so the number no longer aligns with the SNU. Since the Moz DP was submitted, a number of columns were hard coded - PLHIV, TX_NEW, TX_CURR (total and <15) - in the Assumption Input and Target Calculation tab. This also threw off all the HTS figures.

The solution was to go back through the DP, hard coding each SNU list so it was no longer dependent on the DATIM Indicator table and then extract the necessary numbers from each of their source documents for these variables.
