### ISSUE TITLE
Kenya Visualization Request - Due by Friday 2/23

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#17]
Request from Kenya country team - Katana
Approved by Jason R - SI Advisor
Approved by ICPI
Assigned to Shaylee

Need assistance preparing the COP18 Vision presentation.There is one beautiful slide, that is becoming hard to reproduce #21  for Kenya version of the same using APR17 data? - same as GitHub Tickets #4 Burundi and #3 South Sudan Requests [template here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FSouth%20Sudan&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D). 

Redacted slide below for references 
![image](https://user-images.githubusercontent.com/13006198/36421253-c6f321a6-1605-11e8-9807-69f65141ef3b.png)

**Comment by mehtasp** [comment]
Completed and sent Sharepoint link to Jason R since file is too large to attach and send via email. Posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FKenya&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)
