### ISSUE TITLE
Botswana - DataPack - National Targets

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#29]
Submitted by SI Advisor - Jason
@achafetz meeting with Jason to strategize

Botswana's national TX_CURR targets are overinflated. 
Need to get to find a way to get to the same TX_NEW values even after the numerator is lowered from TX_CURR SUBNAT.

**Comment by jb3436** [comment]
I will check in on progress tomorrow @achafetz

**Comment by achafetz** [comment]
Worked with J. Roffenbender the past three days to address the 20% reduction in FY17 TX_CURR_SUBNAT figures. The crux of the issue was that PEPFAR FY19 TX_NEW targets needed to remain at the same level as when the TX_CURR SUBNAT was at the original level. We adjusted the projected TX_CURR_SUBNAT levels forward based on NET_NEW calculations from COP17 data pack and the team figured out the PEPFAR/GoB delta proprotion of NET_NEW, leaving the last element of ART coverage rate to be adjusted.

![image](https://user-images.githubusercontent.com/8933069/36538982-ed8de1aa-17dd-11e8-8dbe-febb017110b1.png)
