### ISSUE TITLE
South Sudan Visualization Request 2/14

### ISSUE THREAD

**Issue by ICPIadmin** [ICPI/COP18#3]
Tat'Yana Kenigsberg (ynf1@cdc.gov) requested 2/14 for ICPI assistance for South Sudan to generate visuals by COB Friday, 2/16. She included sample visuals to use in generating new visualizations (below). The sample visuals are from the RPM COP18 Vision template (slide 21, also attached). in the sharepoint folder here 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by HoustonJamie** [comment]
Adding this here for documentation purposes: Seems like a straightforward request.  My main concern is trying to set  we set up an efficient process for accessing the Q1 data before FV files are released next week, since this will require the data genie site/IM dataset?  Shazad and Abe are you free for a call to discuss whether this can be completed by Friday COB?

**Comment by shazadahmed10** [comment]
fy17 version of SSudan request completed. Creating Fy18Q1 version now

**Comment by ICPIadmin** [comment]
Shazad emailed visualizations to Tat'Yana on 2/16. Products also logged in Sharepoint: 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D
