### ISSUE TITLE
Nigeria DataPack Support from from Roha Due @noon

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#6]
Nigeria changed datapack formulas and needs assistance in making sure they are all correct before presenting to the DCM at Noon. 

- Request submitted by SI advisor
- Approved by ICPI
- Assigned to Aaron C.

**Comment by achafetz** [comment]
@HoustonJamie and I reviewed Nigeria's DP. The team had to adjust formulas due to the fact that Nigeria's TX_CURR numbers are actually going down from FY18 to FY19 targets. The team laid out their work in a Tx assumptions tab in the Data Pack and all make logical sense (will check formulas again to confirm once they complete their updates). We also clarified the targets that needed to be entered into the assumptions tab, rather than writing formulas into the Target tab.
