### ISSUE TITLE
Moz - update Male POS finding tool with Moz Data (requested by Jamie)

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/COP18#67]
**Task:** Use Male POS finding tool built for SSudan/Bots last week to update with Moz data
Approved by Clark
Approved by ICPI
Assigned to Josh

**Steps:** 
-get Moz DataPack from sharepoint
-use only Q3+Q4 data as APR17 (confirm with Jamie)
-use OU xIM data/SAS code
-1 hr LOE once source files are gathered

**Comment by jb3436** [comment]
@jaliasd @HoustonJamie , kindly confirm that Kristine emails approval for this request.

**Comment by shazadahmed10** [comment]
Update: from Josh - FY17 male POS distributions should be based on Q3+Q4, and then applied to real FY17APR total to get FY17 volume of male POS. 
needs to be confirmed*

**Comment by HoustonJamie** [comment]
We are meeting with Clarke and Moz team to discuss at lunch.  She is supportive, but will need to get sign off then.

**Comment by shazadahmed10** [comment]
Update: 
Jamie confirmed that Fy17APR should the reported FY17APR, all quarters. 
Also, KClarke confirmed the need for this. I can commence

**Comment by shazadahmed10** [comment]
Tool updated with Moz data. 
Posted on SharePoint:
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Mozambique/Mozambique%20HTS_Fy19%20Male%20Gap%20Tool.xlsx

**Comment by shazadahmed10** [comment]
update from Jamie:
-Moz used clustered PSNU list in DP; need to get cluster list from Aaron, then rerun dataset with cluster names. (to produce Maputo City Cluster). 
-repost and re-email

**Comment by shazadahmed10** [comment]
Updated tool:

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Mozambique/Mozambique%20HTS_Fy19%20Male%20Gap%20Tool%20V2.xlsx

**Comment by HoustonJamie** [comment]
Shazad

Thanks for making the update for the clusters for Moz. It is coming together nicely…  I went through the tool this morning and noticed one error in the formula and made one addition to the logic.

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FMozambique&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

A couple edits/comments:
-The formulas for % age/sex band allocation are calculating % male or female within an age/sex band but I think they should be calculating the % of finer age/sex band of all <15 HTS_POS
-10-14 is included in the pivot, I think it should be excluded since it would affect the % calculation above once updated
-I added a tab that creates the Rasta table but there are two missing pieces of info to complete. 1) The TX_CURR FY18 and FY19 totals from data pack (columns AB and AO). 2) The FY17 Q4 Age/Sex disaggregation of TX_CURR from FY.

That said, Moz isn’t being pushed to use their age/sex disags.  However Haiti is this week so maybe worth touching base with Audrey this AM to see if this would be helpful or not.

Thanks

Jamie
