### ISSUE TITLE
Haiti request - need help updating a partner & performance slide

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/COP18#85]
I have a slide already done w/ FY17 APR data, but am requesting help updating the exact same info. w/ FY18 Q1 data.  This should only take 30 min. or so to do.  I just have competing requests so am hoping for help.  Thanks!

**Comment by shapaklyak** [comment]
@cnichols3h can you please post the slide and associated file on pepfar.net and link here? Also, what's the timeline for this? Someone here in DC can help out with it if we can get more info.

**Comment by cnichols3h** [comment]
@shapaklyak yes!  I just uploaded the pepfar.net folder under COP18 support and Ad-hoc analyses.  It's a single ppt. slide (the only one in there).  Looking for the exact same analysis, but w/ FY18 Q1 data only.  I have some other details and info. I need to give, but I will follow up w/ whoever is able to help.  Thanks.

**Comment by shapaklyak** [comment]
@cnichols3h ok got it. assigned to @aliyahwakil.

See Slide for reference: 
![image](https://user-images.githubusercontent.com/5234106/36692022-eee0eef6-1b04-11e8-94f5-f3768b403111.png)

Due COB 2/26. 
Partner performance (Results, Targets, % Achievement) for the following indicators by partner) for FY18Q1:
- HTS_TST_POS
- TX_NEW
- TX_CURR
- TX_RET
- TX_PVL

**Comment by cnichols3h** [comment]
@shapaklyak thank you! @aliyahwakil - I will follow up w/ a few details via email.

**Comment by shapaklyak** [comment]
@cnichols3h thanks. should we get started on this or wait for further details from you? What is your timeline for this?

**Comment by cnichols3h** [comment]
@shapaklyak - great.  this is needed now.  i am already in touch w/ @aliyahwakil who is working on this now.  thank you.

**Comment by aliyahwakil** [comment]
working on this now! @cnichols3h catherine just wanted to confirm that SSQH Sud and SSQH Nord. are implemting mech names. Thanks!

**Comment by cnichols3h** [comment]
@aliyahwakil thanks for checking - yes.  the team would like the results and targets combined for SSQH Sud and SSQH Nord.

**Comment by aliyahwakil** [comment]
[https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence](url)

**Comment by aliyahwakil** [comment]
This table does not include tx_ret and tx_plv because this data is not yet available. I used "ICPI_FactView_OU_IM_20180215_v1_3 for this analysis. The excel workbook with subsetted raw data and pivot along with the ppr slide with the table, can be found here. 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by cnichols3h** [comment]
@aliyahwakil - great, thank you.  i've made some additional edits and uploaded a new file to the same folder w/ today's date.  is it possible to add in EID results and targets (see slide 4) and QC slide 3?
@jb3436 @hessionra

**Comment by hessionra** [comment]
@cnichols3h @aliyahwakil I can help with QCing, just sent you a Slack message.

**Comment by aliyahwakil** [comment]
thanks @hessionra. I'm reviewing catherine's updated file and reviewing changes that need to be made.

**Comment by hessionra** [comment]
@aliyahwakil @cnichols3h I'm QCing slide 3 against Pano-- does it need to be QCed against something else? Thanks!

**Comment by cnichols3h** [comment]
@aliyahwakil @hessionra  Pano is fine.  thanks!

**Comment by aliyahwakil** [comment]
just an update. the factview datastes that i analyzed did not have fy18 data for pmtct in order to produce EID table. Katie O. walked through this with me as well.   I'm now checking datim and will check in again on my progress. (will notify Abe after checking datim).

**Comment by hessionra** [comment]
@cnichols3h which dataset did you use to create Slide 3?

**Comment by cnichols3h** [comment]
@hessionra I think I just got the values from Pano. @KatieOC @aliyahwakil thank you. good to verify w. another source as you've done.

**Comment by cnichols3h** [comment]
@aliyahwakil @hessionra - hi!  just checking in on this.

**Comment by aliyahwakil** [comment]
filling in the table now for EID for pmtct_eid and pmtct_hei_pos. What should i use for art?? In regards to ART @KatieOC said the disagg of PMTCT_HEI_POS but probably not reliable since it's so new but
Pano is still displaying TX_NEW <01 to capture proxy linkage of the PMTCT_EID positives (aka PMTCT_HEI_POS). i just wanted to confirm. thanks!

**Comment by cnichols3h** [comment]
@aliyahwakil - good call.  i think you can include the TX_NEW <01 as a proxy since as you said, the new indicator might not be reliable yet.

**Comment by hessionra** [comment]
I QCed Slide 3 against Pano and found a couple things-- I uploaded it onto SharePoint: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

@aliyahwakil @shapaklyak would you be able to compare this to Fact View?

**Comment by KatieOC** [comment]
@cnichols3h I was taking a look at the slides. Just wanted to confirm and apologize if this was already addressed but the last partner listed on the PMTCT slides is Health Service Delivery but for the treatment slides its Health Through Walls, is this correct?

**Comment by KatieOC** [comment]
@aliyahwakil @hessionra the file I pulled from Pano does not include all the partners to verify. Interestingly, my file just has the Partner names and not Mech names and the Partner name GHESKIO = GHESKIO 1969 from your PowerPoint so to me that means the GHESKIO 1969 represents all the GHESKIO mech names but will need Pano back up to verify.

**Comment by KatieOC** [comment]
@cnichols3h I know you are just answering data requests but is there room to insert some variation to this request? This is specific to linkage for both the treatment and PMTCT slides. You will note a common theme of TX_NEW and PMTCT_ART being higher than positives for some partners and terribly low for some partners. Would they be open to showing linkage by these partners? It would be TX_NEW/HTS_POS and for PMTCT_ART/PMTCT_STAT_POS and for infants it is TX_NEW<01/PMTCT_EID(0-12months)

**Comment by aliyahwakil** [comment]
@cnichols3h i uploaded to sharepoint the power point with PMTCT EID table added.  File is titled Partner performance_FY17 APR_targets_percent achievement_27Feb2018_AAW . IM BEST was not in original table template but I added it because it did have FY18 data. Thanks @KatieOC for help with QC!

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D

**Comment by cnichols3h** [comment]
@aliyahwakil @KatieOC - thank you!  this is great.  i appreciate your help.  i'm finalizing and will upload again.
