### ISSUE TITLE
Vietnam -> consultation around clustering

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#91]
J.Buehler came by looking into the possibility of clustering some provinces for Vietnam.  They are still uncertain about doing it, but wanted to know the process. They will not be using the site import since they have so many new sites, so this will only affect data pack and disagg creation. I sent along the info they need to provide and they will follow up later today.

**Comment by jb3436** [comment]
We didn't hear back from them, so we are closing out the ticket since it is unlikely that they will take action. The consultation with Aaron provided sufficient information for them to make a decision about how to proceed. Hearing no additional feedback, it is unlikely that they will change anything.
